package ru.progpuppers.simmsearch.presentation.deviceAdd

import android.bluetooth.BluetoothClass
import android.os.ParcelUuid
import androidx.compose.runtime.MutableState
import androidx.compose.runtime.mutableStateOf
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.launch
import ru.progpuppers.simmsearch.domain.model.BthDevice
import ru.progpuppers.simmsearch.domain.model.BthDeviceSaved
import ru.progpuppers.simmsearch.domain.repository.DeviceRepository
import javax.inject.Inject

@HiltViewModel
class DeviceSaveViewModel @Inject constructor(
    private val deviceRepository: DeviceRepository,
) : ViewModel() {

    val state = mutableStateOf(BthDeviceSaveState())

    fun saveDevice() {
        // todo: нужно ли возвращать результат что добавлен
        val saveDevice = state.value.toBthDeviceSaved()
        viewModelScope.launch { deviceRepository.save(saveDevice) }
    }
}

// todo: мб в BthDeviceSaveState лишняя вложенность с mutableStateLists
data class BthDeviceSaveState(
    val name: MutableState<String> = mutableStateOf(""),
    val address: String = "",
    val type: Int = 0,
    val uuids: List<ParcelUuid> = emptyList(),
    val bluetoothClass: BluetoothClass? = null,
    val bondState: Int = 0,
    var description: MutableState<String> = mutableStateOf("")
) {

    fun toBthDeviceSaved(): BthDeviceSaved = BthDeviceSaved(
        id = 0L,    // todo: перепишет ли рум id по autogenerated
        name = name.value,
        address = address,
        description = description.value // todo: мб луше сейвить в бд null
    )

    companion object {
        fun of(device: BthDevice): BthDeviceSaveState = BthDeviceSaveState(
            name = mutableStateOf(device.name),
            address = device.address,
            type = device.type,
            uuids = device.uuids,
            bluetoothClass = device.bluetoothClass,
            bondState = device.bondState,
            description = mutableStateOf(""),
        )
    }
}